IMAG_backend/IMAG/users/views.py
import os
from functools import wraps
import ast
from flask import *
from flask import Blueprint, request, render_template
from sqlalchemy.sql.elements import or_
from libs.db import DBSession, Conf, Account, Tch, Stu, Jn, Patent, Prog, Comp, Mono, Soft, Gra, Honor, Course
from login.views import save_avatar, login_required, save_resume

users_bp = Blueprint('users', import_name='users')
users_bp.template_folder = './templates'
users_bp.static_folder = './static'



# 实验室成员展示页面
@users_bp.route('/people_page', methods=('GET', 'POST'))
def people_page():
    sessions = DBSession()
    faculty = sessions.query(Tch).join(Account, Tch.account == Account.account).filter(
        or_(Tch.tch_classify == '博士生导师', Tch.tch_classify == '硕士生导师', Tch.tch_classify == '其他老师'),
        Account.examine == '1')
    ass_faculty = sessions.query(Tch).join(Account, Tch.account == Account.account).filter(Tch.tch_classify == '其他老师',
                                                                                           Account.examine == '1').all()
    PhD = sessions.query(Stu).join(Account, Stu.account == Account.account).filter(
        Stu.stu_classify == '博士生', Account.examine == '1').all()
    ME = sessions.query(Stu).join(Account, Stu.account == Account.account).filter(Stu.stu_classify == '硕士生',
                                                                                  Account.examine == '1').all()
    graduates = sessions.query(Gra).all()
    sessions.close()
    return render_template('people_page.html', faculty=faculty, ass_faculty=ass_faculty, PhD=PhD, ME=ME,
                           graduates=graduates)


# 学生个人资料
@users_bp.route('/stu_info/<account>/', methods=('GET', 'POST'))
def stu_info(account):
    sessions = DBSession()
    stu_info = sessions.query(Stu).filter(Stu.account == account).first()
    if request.method == 'POST':
        stu_account = sessions.query(Account).filter(Account.account == account).first()
        stu_info.stu_classify = stu_info.stu_classify
        stu_info.phone = stu_info.phone
        stu_info.email = stu_info.email
        if request.files['avatar']:
            save_avatar(stu_info.account, request.files['avatar'])
        if request.files['resume']:
            save_resume(stu_info.account, request.files['resume'])
        if request.form.get('password', '') != '':
            stu_account.password = request.form.get('password', '')
        sessions.commit()
        return redirect(url_for("users.stu_page", account=stu_info.account))
    return render_template('stu_info.html', stu_info=stu_info, account_url=stu_info)


# 教师个人资料
@users_bp.route('/tch_info/<account>/', methods=('GET', 'POST'))
def tch_info(account):
    sessions = DBSession()
    tch_info = sessions.query(Tch).join(Account, Account.account == Tch.account).filter(Tch.account == account).first()
    if request.method == 'POST':
        tch_account = sessions.query(Account).filter(Account.account == account).first()
        tch_info.tch_classify = request.form.get('classify', '').strip()
        tch_info.phone = request.form.get('phone', '').strip()
        tch_info.email = request.form.get('email', '').strip()
        tch_info.profile = request.form.get('profile', '').strip()
        if request.files['avatar']:
            save_avatar(tch_info.account, request.files['avatar'])
        if request.files['resume']:
            save_resume(tch_info.account, request.files['resume'])
        if request.form.get('password', '') != '':
            tch_account.password = request.form.get('password')
        sessions.commit()
        return redirect(url_for("users.tch_page", account=tch_info.account))
    return render_template('tch_info.html', tch_info=tch_info, account_url=tch_info)


# 学生个人主页
@users_bp.route('/stu_page/<account>/', methods=('GET', 'POST'))
def stu_page(account):
    sessions = DBSession()
    stu_info = sessions.query(Stu).filter(Stu.account == account).first()
    conf_info_dict = paper(stu_info.conference, Conf)
    jn_info_dict = paper(stu_info.journal, Jn)
    patent_info = gain(stu_info.patent, Patent)
    prog_info = gain(stu_info.program, Prog)
    mono_info = gain(stu_info.monograph, Mono)
    soft_info = gain(stu_info.software, Soft)
    comp_info = gain(stu_info.competition, Comp)
    sessions.close()
    return render_template('stu_page.html', stu_info=stu_info, conf_info_dict=conf_info_dict, jn_info_dict=jn_info_dict,
                           patent_info=patent_info, prog_info=prog_info, mono_info=mono_info, soft_info=soft_info,
                           comp_info=comp_info, account_url=stu_info)


# 教师个人主页
@users_bp.route('/tch_page/<account>/', methods=('GET', 'POST'))
def tch_page(account):
    sessions = DBSession()
    data = sessions.query(Tch).filter(Tch.account == account).first().display
    data = eval(data)
    print(data)
    tch_info = sessions.query(Tch).filter(Tch.account == account).first()
    conf_info_dict = paper(tch_info.conference, Conf, data['conf'])
    jn_info_dict = paper(tch_info.journal, Jn, data['jn'])
    patent_info = gain(tch_info.patent, Patent, data['patent'])
    prog_info = gain(tch_info.program, Prog, data['prog'])
    mono_info = gain(tch_info.monograph, Mono, data['mono'])
    soft_info = gain(tch_info.software, Soft, data['soft'])
    comp_info = gain(tch_info.competition, Comp, data['comp'])
    honor_info = gain(tch_info.honor, Honor, data['honor'])
    course_info = gain(tch_info.course, Course, data['course'])
    return render_template('tch_page.html', tch_info=tch_info, conf_info_dict=conf_info_dict, jn_info_dict=jn_info_dict,
                           patent_info=patent_info, prog_info=prog_info, mono_info=mono_info, soft_info=soft_info,
                           comp_info=comp_info, honor_info=honor_info, course_info=course_info, account_url=tch_info)


# 教师个人主页
@users_bp.route('/tch_page_database/<account>/', methods=('GET', 'POST'))
def tch_page_database(account):
    sessions = DBSession()
    tch_info = sessions.query(Tch).filter(Tch.account == account).first()
    conf_info_dict = paper(tch_info.conference, Conf)
    jn_info_dict = paper(tch_info.journal, Jn)
    patent_info = gain(tch_info.patent, Patent)
    prog_info = gain(tch_info.program, Prog)
    mono_info = gain(tch_info.monograph, Mono)
    soft_info = gain(tch_info.software, Soft)
    comp_info = gain(tch_info.competition, Comp)
    honor_info = gain(tch_info.honor, Honor)
    course_info = gain(tch_info.course, Course)
    return render_template('tch_page_database.html', tch_info=tch_info, conf_info_dict=conf_info_dict,
                           jn_info_dict=jn_info_dict,
                           patent_info=patent_info, prog_info=prog_info, mono_info=mono_info, soft_info=soft_info,
                           comp_info=comp_info, honor_info=honor_info, course_info=course_info, account_url=tch_info)


# 教师个人主页
@users_bp.route('/tch_page_public/<id>/', methods=('GET', 'POST'))
def tch_page_public(id):
    sessions = DBSession()
    data = sessions.query(Tch).filter(Tch.id == id).first().display
    data = eval(data)
    tch_info = sessions.query(Tch).filter(Tch.id == id).first()
    conf_info_dict = paper(tch_info.conference, Conf, data['conf'])
    jn_info_dict = paper(tch_info.journal, Jn, data['jn'])
    patent_info = gain(tch_info.patent, Patent, data['patent'])
    prog_info = gain(tch_info.program, Prog, data['prog'])
    mono_info = gain(tch_info.monograph, Mono, data['mono'])
    soft_info = gain(tch_info.software, Soft, data['soft'])
    comp_info = gain(tch_info.competition, Comp, data['comp'])
    honor_info = gain(tch_info.honor, Honor, data['honor'])
    course_info = gain(tch_info.course, Course, data['course'])
    sessions.commit()
    return render_template('tch_page_public.html', tch_info=tch_info, conf_info_dict=conf_info_dict,
                           jn_info_dict=jn_info_dict,
                           patent_info=patent_info, prog_info=prog_info, mono_info=mono_info, soft_info=soft_info,
                           comp_info=comp_info, honor_info=honor_info, course_info=course_info, account_url=tch_info)


# 用户主页修改后端
@users_bp.route('/user_database', methods=('GET', 'POST'))
def user_database():
    sessions = DBSession()
    data = request.get_json()
    account = data['account']
    conf = data['conf']
    prog = data['prog']
    jn = data['jn']
    course = data['course']
    patent = data['patent']
    honor = data['honor']
    comp = data['comp']
    mono = data['mono']
    soft = data['soft']
    user_info = sessions.query(Tch).filter(Tch.account == account).first()
    if user_info is None:
        user_info = sessions.query(Stu).filter(Stu.account == account).first()
    dic_conf = dict()
    dic_jn = dict()
    for item in conf:
        id = item['id']
        list = eval(item['list'])
        dic_conf[str(id)] = list
    for item in jn:
        id = item['id']
        list = eval(item['list'])
        dic_jn[str(id)] = list
    user_info.conference = str(dic_conf)
    user_info.journal = str(dic_jn)
    user_info.program = str(prog)
    user_info.software = str(soft)
    user_info.course = str(course)
    user_info.patent = str(patent)
    user_info.honor = str(honor)
    user_info.monograph = str(mono)
    user_info.competition = str(comp)
    sessions.commit()
    sessions.close()
    response = dict()
    response['message'] = "保存成功!"
    return json.dumps(response, ensure_ascii=False)


# 用户主页修改后端
@users_bp.route('/user_page_back', methods=('GET', 'POST'))
def user_page_back():
    sessions = DBSession()
    data = request.get_json()
    account = data['account']
    display = data['display']
    user_info = sessions.query(Tch).filter(Tch.account == account).first()
    if user_info is None:
        user_info = sessions.query(Stu).filter(Stu.account == account).first()
    user_info.display = str(display)
    sessions.commit()
    sessions.close()
    response = dict()
    response['message'] = "保存成功!"

IMAG_backend/IMAG/users/templates/people_page.html
{% extends 'base.html' %}

{% block all %}


{#    Faculty分割线#}
    <div class="row">
{#        <div class="col-md-1"></div>#}
        <div class="col-md-4">
            <h2><span class="glyphicon glyphicon-user" aria-hidden="true"> Faculty </span></h2>
        </div>
{#        <div class="col-md-10">#}
{#            <br>#}
{#            <hr/>#}
{#        </div>#}
    </div>
    <br>
    {#    Faculty#}

    <div class="row">
{#        <div class="col-md-1"></div>#}
        {% for row in faculty %}
        <div class="col-md-6">
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="./static/avatar/{{ row.account }}.jpg" alt="{{ row.account }}" width="100px" height="120">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{ row.name }}</h4>
                        <p>Professor at Nanjing University of Science and Technology (NJUST)</p>
                        <a href="/users/tch_page_public/{{ row.id }}">个人主页</a>
                        <p>
                            <address>
                                Email: {{ row.email |default('', boolean=True) }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Tel:{{ row.phone|default('', boolean=True) }}
                            </address>
                        </p>
                    </div>
                </div>
        </div>
{#        <div class="col-md-1"></div>#}
     {% endfor %}
    </div>


    {#    Ph.D Candidate分割线#}
     <div class="row">
        <div class="col-md-4">
            <h2><span class="glyphicon glyphicon-user" aria-hidden="true"> Ph.D Candidate </span></h2>
        </div>
{#        <div class="col-md-8">#}
{#            <br>#}
{#            <hr/>#}
{#        </div>#}
    </div>
    <br>
    {#    Ph.D Candidate#}

    <div class="row">
        {% for row in PhD %}
{#        <div class="col-md-1"></div>#}
        <div class="col-md-4">
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="./static/avatar/{{ row.account }}.jpg" alt="{{ row.account }}" width=100px" height="120px">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{ row.Eng_name }}| {{ row.name }}</h4>
                    <p>September 2016 - now</p>
                        <p>
                           <address>
                                Email: {{ row.email |default('', boolean=True) }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Tel:{{ row.phone|default('', boolean=True) }}
                           </address>
                        </p>
                    </div>
                </div>
        </div>
     {% endfor %}
    </div>

<br>


    <div class="row">
        <div class="col-md-4">
            <h2><span class="glyphicon glyphicon-user" aria-hidden="true"> M.E Students </span></h2>
        </div>
{#        <div class="col-md-8">#}
{#            <br>#}
{#            <hr/>#}
{#        </div>#}
    </div>
    <br>

    {#    M.E Students#}
    <div class="row">
        {% for row in ME %}
{#        <div class="col-md-1"></div>#}
        <div class="col-md-4">
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="./static/avatar/{{ row.account }}.jpg" alt="{{ row.account }}" width="80px" height="96px">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{ row.name }}</h4>
                        <p>September 2016 - now</p>
                        <p>
                            <address>
                                Email: {{ row.email |default('', boolean=True) }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Tel:{{ row.phone|default('', boolean=True) }}
                           </address>
                        </p>
                    </div>
                </div>
        </div>
     {% endfor %}
    </div>




    <script>
    $(document).ready(function() {
        document.getElementById("peo_id").className="active";
 })
</script>
{% endblock %}

IMAG_backend/IMAG/users/templates/stu_info.html
{% extends 'base_stu.html' %}
{% block head %}

{% endblock %}


{% block center %}


    <form action="{{url_for('users.stu_info',account=stu_info.account)}}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="media">
              <div class="media-left media-middle">
                  <img class="media-object" src="/users/static/avatar/{{ stu_info.account }}.jpg" width="100px" height="">
                <input type="file" name="avatar"   accept="image/gif, image/jpeg, image/png, image/jpg" >
              </div>
              <div class="media-body">
                <h4 class="media-heading">{{ stu_info.account }}</h4>
                个人简介：
                  <textarea type="text" class="form-control" rows="3"  name="profile">{{ stu_info.profile }}</textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">姓名</label>
        <input type="text" class="form-control" id="exampleInputPassword1" value="{{ stu_info.name }}" name="name">
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">英文名</label>
        <input type="text" class="form-control" value="{{ stu_info.Eng_name }}" name="Eng_name">
      </div>
        <div class="form-group">
        <label for="exampleInputEmail1">用户类别</label><br>
            <label class="radio-inline">
          <input type="radio" name="classify" id="inlineRadio4" value="博士生"> 博士生
        </label>
            <label class="radio-inline">
          <input type="radio" name="classify" id="inlineRadio5" value="硕士生"> 硕士生
        </label>
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">重置密码</label>
        <input type="password" class="form-control" name="password">
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">Tel</label>
        <input type="text" class="form-control" value="{{ stu_info.phone }}" name="phone">
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">Email</label>
        <input type="text" class="form-control" value="{{ stu_info.email }}" name="email">
      </div>
        <div class="form-group">
        <label for="exampleInputFile">个人简历</label>
        <input type="file" id="exampleInputFile" name="resume">
      </div>
    {#  <div class="checkbox">#}
    {#    <label>#}
    {#      <input type="checkbox"> Check me out#}
    {#    </label>#}
    {#  </div>#}
      <button type="submit" class="btn btn-default">更改
      </button>
</form>
 <script >
    var stu = "{{stu_info.stu_classify}}"
    $(document).ready(function() {
            if (stu === "博士生导师") {
                document.getElementById("inlineRadio1").checked = true;
            } else if (stu === "硕士生导师") {
                document.getElementById("inlineRadio2").checked = true;
            } else if (stu === "其他老师") {
                document.getElementById("inlineRadio3").checked = true;
            } else if (stu === "博士生") {
                document.getElementById("inlineRadio4").checked = true;
            } else {
                document.getElementById("inlineRadio5").checked = true;
            }
        }
    )

        function CheckBoxChs() {
            var obj = document.getElementsByName('classify');
            var objYN = false;
            var i;
            for (i = 0; i < obj.length; i++) {
                if (obj[i].checked == true) {
                    objYN = true;
                    break;
                }
            }
            return objYN;
        }

        function apply() {
            if (CheckBoxChs() === false) {
                alert("至少选择一个.");
                return;
            } else document.forms[0].submit();
        }

</script>
{% endblock %}

IMAG_backend/IMAG/users/templates/tch_info.html
{% extends 'base_tch.html' %}
{% block head %}

{% endblock %}


{% block center %}


    <form action="{{url_for('users.tch_info',account=tch_info.account)}}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="media">
              <div class="media-left media-middle">
                  <img class="media-object" src="/users/static/avatar/{{ tch_info.account }}.jpg" width="100px" height="" alt="">
                 <input type="file" name="avatar"   accept="image/gif, image/jpeg, image/png, image/jpg" >
              </div>
              <div class="media-body">
                <h4 class="media-heading">{{ tch_info.account }}</h4>
                个人简介：
                  <textarea type="text" class="form-control" rows="3"  name="profile">{{ tch_info.profile }}</textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">姓名</label>
        <input type="text" class="form-control" id="exampleInputPassword1" value="{{ tch_info.name }}" name="name">
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">英文名</label>
        <input type="text" class="form-control" value="{{ tch_info.Eng_name }}" name="Eng_name">
      </div>

            <div class="form-group">
        <label for="exampleInputEmail1">用户类别</label><br>
        <label class="radio-inline">
          <input type="radio" name="classify" id="inlineRadio1" value="博士生导师"> 博士生导师
        </label>
        <label class="radio-inline">
          <input type="radio" name="classify" id="inlineRadio2" value="硕士生导师"> 硕士生导师
        </label>
            <label class="radio-inline">
          <input type="radio" name="classify" id="inlineRadio3" value="其他老师"> 其他老师
        </label>
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">重置密码</label>
        <input type="password" class="form-control" id="password1" name="password">
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">Tel</label>
        <input type="text" class="form-control" value="{{ tch_info.phone }}" name="phone">
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">Email</label>
        <input type="text" class="form-control" value="{{ tch_info.email }}" name="email">
      </div>
        <div class="form-group">
        <label for="exampleInputFile">个人简历</label>
        <input type="file" id="exampleInputFile" name="resume">
      </div>
    {#  <div class="checkbox">#}
    {#    <label>#}
    {#      <input type="checkbox"> Check me out#}
    {#    </label>#}
    {#  </div>#}
      <button type="submit" class="btn btn-default">更改
      </button>
</form>
 <script >
    var tch = "{{tch_info.tch_classify}}"
    $(document).ready(function(){
    if (tch ==="博士生导师"){
       document.getElementById("inlineRadio1").checked = true;}
        {#$("#inlineRadio1").attr(checked, true);}#}
    else if( tch==="硕士生导师"){
       document.getElementById("inlineRadio2").checked = true;}
        {#$("#inlineRadio2").attr(checked, true);}#}
    else if( tch==="其他老师"){
       document.getElementById("inlineRadio3").checked = true;}
    else if( tch==="博士生"){
       document.getElementById("inlineRadio4").checked = true;}
    else{
        document.getElementById("inlineRadio5").checked = true;}

}); </script>
{% endblock %}

IMAG_backend/IMAG/users/templates/tch_page_public.html
{% extends 'base.html' %}
{%  block style %}
     .atitle{
    font-size:40px;
    font-family:"微软雅黑";
    padding:20px 0px;
    }
    .li_name{
    font-size:15px;
    font-family:"微软雅黑";
    }
    li{
    line-height:40px;
    display:flex;
    justify-content:space-between;
    }
{%  endblock %}
{% block center %}


    <div class="media">
        <div class="media-left media-middle">
            <a href="#">
                <img class="media-object" src="../../static/avatar/{{ tch_info.account }}.jpg"
                     alt="{{ tch_info.account }}" width="180px" height="" id="imag_id">
            </a>
        </div>
        <div class="media-body">
            <h3 class="media-heading">{{ tch_info.Eng_name }}</h3>

            <p><a src="http://www.njust.edu.cn/">Nanjing University of Science and Technology</a></p>


            <p>Email : {{ tch_info.email }}</p>

             <p id="profile">{{ tch_info.profile }}<a onclick="tran();">[中文版]</a></p>

        </div>
    </div>


    <hr>
    <ul>
        <div class="atitle" id="title_jn">论文</div>
            {% for row in jn_info_dict %}
            <li class="jn_li" id="{{ row.id }}" value="{{ row['author'] }}">
                <div class="li_name">{{ row.name}}
            {% for auth in row['author'] %}
                {{ auth }}
            {% endfor %}
                </div>
            </li>
           {% endfor %}
         <div class="atitle" id="title_con">会议</div>
        {% for row  in conf_info_dict %}
            <li class="conf_li" id="{{ row.id }}" value="{{ row['author'] }}">
                <div class="li_name">{{ row.name }}
                {% for auth in row['author'] %}
                    {{ auth }}
                {% endfor %}
                </div>
            </li>
        {% endfor %}
    <div class="atitle" id="title_patent">专利</div>
        {% for row in patent_info %}
            <li class="patent_li" id="{{ row.id }}" >
                <div class="li_name">{{ row.name}} </div>
            </li>
        {% endfor %}
<div class="atitle" id="title_honor">荣誉</div>
        {% for row in honor_info %}
            <li class="honor_li" id="{{ row.id }}" >
                 <div class="li_name">{{ row.name}} </div>
            </li>
        {% endfor %}
    <div class="atitle" id="title_pro">项目</div>
        {% for row in prog_info %}
            <li class="prog_li" id="{{ row.id }}" >
           <div class="li_name">{{ row.name}} </div>
            </li>
        {% endfor %}
<div class="atitle" id="title_course">课程</div>
        {% for row in course_info %}
            <li class="course_li" id="{{ row.id }}" >
                 <div class="li_name">{{ row.name}} </div>
            </li>
        {% endfor %}
    <div class="atitle" id="title_comp">竞赛</div>
        {% for row in comp_info %}
            <li class="comp_li" id="{{ row.id }}" >
                 <div class="li_name">{{ row.name}} </div>
            </li>
        {% endfor %}
    <div class="atitle" id="title_mono">专著</div>
        {% for row in mono_info %}
            <li class="mono_li" id="{{ row.id }}" >
               <div class="li_name">{{ row.name}} </div>
            </li>
        {% endfor %}
    <div class="atitle" id="title_soft">软著</div>
        {% for row in soft_info %}
            <li class="soft_li" id="{{ row.id }}">
                <div class="li_name">{{ row.name}} </div>
            </li>
        {% endfor %}

    {{ others_info }}

    </ul>
<script>
$(document).ready(function(){
         const jn={{ jn_info_dict|tojson }};
         const con= {{ conf_info_dict|tojson }};
         const patent={{ patent_info|tojson}};
         const honor={{ honor_info|tojson }};
         const course={{ course_info|tojson }};
         const comp={{ comp_info|tojson }};
         const mono={{ mono_info|tojson }};
         const soft={{ soft_info|tojson }};
         const pro={{ prog_info|tojson }};
        if(jn.length===0) $("#title_jn").remove();
        if(con.length===0) $("#title_con").remove();
        if(patent.length===0) $("#title_patent").remove();
        if(honor.length===0) $("#title_honor").remove();
        if(course.length===0) $("#title_course").remove();
        if(comp.length===0) $("#title_comp").remove();
        if(mono.length===0) $("#title_mono").remove();
        if(soft.length===0) $("#title_soft").remove();
        if(pro.length===0) $("#title_pro").remove();
    })
     var Serve1={
     profile_eng:{{ tch_info.profile|tojson }},
     profile_ch:{{ tch_info.profile_c|tojson }},
     account:{{ tch_info.account|tojson }}
 }
    tranx=function (){
      pro=document.getElementById("profile")
      temp=document.createElement("a")
      temp.innerText="[中文版]"
     pro.innerText=Serve1.profile_eng
     temp.onclick=tran
     pro.appendChild(temp)
 }
  tran=function (){
        pro=document.getElementById("profile")
        temp=document.createElement("a")
        temp.innerText="[English Version]"
        temp.onclick=tranx
        pro.innerText=Serve1.profile_ch
        pro.appendChild(temp)
       }
</script>
{% endblock %}